const ACTION_TYPES = {
  REST_LOADING: "REST_LOADING",
  REST_ERROR: "REST_ERROR",
  REST_SUCCES: "REST_SUCCES",
  BASKET_LOADING: "BASKET_LOADING",
  BASKET_ERROR: "BASKET_ERROR",
  BASKET_SUCCES: "BASKET_SUCCES",
  CREATE_ITEM: "CREATE_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  REMOVE_ITEM: "ROMOVE_ITEM",
};

export default ACTION_TYPES;
